### ISSUE TITLE
Runner.ipynb reports WARN engine run error

### ISSUE THREAD

**Issue by Cortze** [libp2p/gossipsub-hardening#14]
Hey there, I've been trying to launch a small simulation to test the gossipsub-hardening and I faced few problems. I really hope you can enlight me with them.

**Additional info:**
Gossipsub-hardening Commit: 05e0e18ae1d81494016aa33d171dee0ffc8d4d76
Processor Architecture: x86_64
go version: go1.14.4 linux/amd64
docker version: 19.03.11
testground version: 0.5.3

**Faced problem**
Launching the `testground daemon` on one terminal and the `jupyter notebook` (on the proper python3 venv) on another one, I tried to run the simulation few times. 
The configuration:
Daemon Endpoint -> http://localhost:8042 (the testground daemon listens there)
Builder -> docker:go
Runner -> local:docker
10 publisher nodes
2 lurker nodes

when I launch the simulation the received WARN log info is the following:

> Aug 11 09:55:56.169607	INFO	created container	{"req_id": "aa3ff200", "container_name": "testground-sidecar", "id": "1441f98d0535a06a84176ea9879903e96cd8542663c58329833613e275d5e762"}
> Aug 11 09:55:56.169664	INFO	starting container	{"req_id": "aa3ff200", "container_name": "testground-sidecar", "id": "1441f98d0535a06a84176ea9879903e96cd8542663c58329833613e275d5e762"}
> Aug 11 09:55:56.649180	INFO	started container	{"req_id": "aa3ff200", "container_name": "testground-sidecar", "id": "1441f98d0535a06a84176ea9879903e96cd8542663c58329833613e275d5e762"}
> Aug 11 09:55:56.649899	WARN	engine run error: healthcheck fixes failed; aborting:
> Checks:
> - local-outputs-dir: ok; directory exists.
> - control-network: ok; network exists.
> - local-grafana: failed; container not found.
> - local-redis: failed; container not found.
> - local-influxdb: failed; container not found.
> - sidecar-container: failed; container not found.
> Fixes:
> - local-outputs-dir: unnecessary; 
> - control-network: unnecessary; 
> - local-grafana: failed; failed to start container.
> - local-redis: ok; container started
> - local-influxdb: ok; container started
> - sidecar-container: ok; container started
> 	{"req_id": "aa3ff200"}
> 
> >>> Error:
> 
> engine run error: healthcheck fixes failed; aborting:
> Checks:
> - local-outputs-dir: ok; directory exists.
> - control-network: ok; network exists.
> - local-grafana: failed; container not found.
> - local-redis: failed; container not found.
> - local-influxdb: failed; container not found.
> - sidecar-container: failed; container not found.
> Fixes:
> - local-outputs-dir: unnecessary; 
> - control-network: unnecessary; 
> - local-grafana: failed; failed to start container.
> - local-redis: ok; container started
> - local-influxdb: ok; container started
> - sidecar-container: ok; container started

Any idea of what can it be? thanks in advance.

**Comment by yusefnapora** [comment]
It looks like testground can’t find the docker containers it needs for the local:docker runner. You could try running `make docker` inside the testground repo, then try running the test again

**Comment by Cortze** [comment]
Seems that the only problem is the local-grafana container even after making `make docker`

> Aug 18 13:55:44.593724  WARN    engine run error: healthcheck fixes failed; 
> aborting:
> Checks:
> - local-outputs-dir: ok; directory exists.
> - control-network: ok; network exists.
> - local-grafana: failed; container not found.
> - local-redis: ok; container state: running
> - local-influxdb: ok; container state: running
> - sidecar-container: ok; container state: running
> Fixes:
> - local-outputs-dir: unnecessary; 
> - control-network: unnecessary; 
> - local-grafana: failed; failed to start container.
> - local-redis: unnecessary; 
> - local-influxdb: unnecessary; 
> - sidecar-container: unnecessary; 
>         {"req_id": "bc421857"}

but the image is locally downloaded:
docker image ls
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE

> 16a94e12f2c9              latest              07597608d153        26 minutes ago      31.3MB
> c46a249bb94b              latest              07597608d153        26 minutes ago      31.3MB
> d3e6461cbb3a              latest              07597608d153        26 minutes ago      31.3MB
> tg-plan-pubsub            07597608d153        07597608d153        26 minutes ago      31.3MB
> sigp/lighthouse           latest              9d837981a9fa        28 hours ago        157MB
>>> bitnami/grafana           latest              694a7c1715a4        2 days ago          465MB
> 12b7ad10ed5a              latest              d1e2767dfc7c        7 days ago          31.3MB
> 2b8f93a7a770              latest              d1e2767dfc7c        7 days ago          31.3MB
> c75eca9fab6b              latest              d1e2767dfc7c        7 days ago          31.3MB
> tg-plan-pubsub            d1e2767dfc7c        d1e2767dfc7c        7 days ago          31.3MB
> 85427a09bcad              latest              84f5a24276c8        7 days ago          31.3MB
> tg-plan-pubsub            84f5a24276c8        84f5a24276c8        7 days ago          31.3MB
> 8f6f0386a1c6              latest              3bc2e263619c        8 days ago          31.3MB
> c37ef8929229              latest              3bc2e263619c        8 days ago          31.3MB
> tg-plan-pubsub            3bc2e263619c        3bc2e263619c        8 days ago          31.3MB
> 3e11f1cb54a9              latest              3bc2e263619c        8 days ago          31.3MB
> 78f01cd821f5              latest              3bc2e263619c        8 days ago          31.3MB
> 811dae235b1c              latest              3bc2e263619c        8 days ago          31.3MB
> 26d0decd7b1a              latest              7ffb3b6faeee        11 days ago         31.3MB
> d92c090b869e              latest              7ffb3b6faeee        11 days ago         31.3MB
> e8bcc2da0bf5              latest              7ffb3b6faeee        11 days ago         31.3MB
> tg-plan-pubsub            7ffb3b6faeee        7ffb3b6faeee        11 days ago         31.3MB
> iptestground/sidecar      edge                86d7a216e5bd        11 days ago         198MB
> iptestground/testground   edge                62a89121c0bf        11 days ago         870MB
> influxdb                  1.8                 376a04c5c7e5        12 days ago         304MB
> golang                    1.14-buster         132b2ef94b55        13 days ago         810MB
> redis                     latest              1319b1eaa0b7        13 days ago         104MB
> debian                    buster              ee11c54e6bb7        13 days ago         114MB
> golang                    1.14.4-buster       00d970a31ef2        7 weeks ago         810MB
> ubuntu                    latest              74435f89ab78        2 months ago        73.9MB
> busybox                   1.31.1-glibc        7a2331af2292        2 months ago        5.2MB
> goproxy/goproxy           latest              e5878c746779        3 months ago        532MB
> hello-world               latest              bf756fb1ae65        7 months ago        13.3kB

**Comment by Cortze** [comment]
Seems that the only problem is the local-grafana container even after
making make docker

Aug 18 13:55:44.593724 WARN engine run error: healthcheck fixes failed;
aborting:
Checks:

   - local-outputs-dir: ok; directory exists.
   - control-network: ok; network exists.
   - local-grafana: failed; container not found.
   - local-redis: ok; container state: running
   - local-influxdb: ok; container state: running
   - sidecar-container: ok; container state: running
   Fixes:
   - local-outputs-dir: unnecessary;
   - control-network: unnecessary;
   - local-grafana: failed; failed to start container.
   - local-redis: unnecessary;
   - local-influxdb: unnecessary;
   - sidecar-container: unnecessary;
   {"req_id": "bc421857"}

but the image is locally downloaded:
docker image ls

REPOSITORY TAG IMAGE ID CREATED SIZE

16a94e12f2c9 latest 07597608d153 26 minutes ago 31.3MB
c46a249bb94b latest 07597608d153 26 minutes ago 31.3MB
d3e6461cbb3a latest 07597608d153 26 minutes ago 31.3MB
tg-plan-pubsub 07597608d153 07597608d153 26 minutes ago 31.3MB
sigp/lighthouse latest 9d837981a9fa 28 hours ago 157MB
->> bitnami/grafana latest 694a7c1715a4 2 days ago 465MB
12b7ad10ed5a latest d1e2767dfc7c 7 days ago 31.3MB
2b8f93a7a770 latest d1e2767dfc7c 7 days ago 31.3MB
c75eca9fab6b latest d1e2767dfc7c 7 days ago 31.3MB
tg-plan-pubsub d1e2767dfc7c d1e2767dfc7c 7 days ago 31.3MB
85427a09bcad latest 84f5a24276c8 7 days ago 31.3MB
tg-plan-pubsub 84f5a24276c8 84f5a24276c8 7 days ago 31.3MB
8f6f0386a1c6 latest 3bc2e263619c 8 days ago 31.3MB
c37ef8929229 latest 3bc2e263619c 8 days ago 31.3MB
tg-plan-pubsub 3bc2e263619c 3bc2e263619c 8 days ago 31.3MB
3e11f1cb54a9 latest 3bc2e263619c 8 days ago 31.3MB
78f01cd821f5 latest 3bc2e263619c 8 days ago 31.3MB
811dae235b1c latest 3bc2e263619c 8 days ago 31.3MB
26d0decd7b1a latest 7ffb3b6faeee 11 days ago 31.3MB
d92c090b869e latest 7ffb3b6faeee 11 days ago 31.3MB
e8bcc2da0bf5 latest 7ffb3b6faeee 11 days ago 31.3MB
tg-plan-pubsub 7ffb3b6faeee 7ffb3b6faeee 11 days ago 31.3MB
iptestground/sidecar edge 86d7a216e5bd 11 days ago 198MB
iptestground/testground edge 62a89121c0bf 11 days ago 870MB
influxdb 1.8 376a04c5c7e5 12 days ago 304MB
golang 1.14-buster 132b2ef94b55 13 days ago 810MB
redis latest 1319b1eaa0b7 13 days ago 104MB
debian buster ee11c54e6bb7 13 days ago 114MB
golang 1.14.4-buster 00d970a31ef2 7 weeks ago 810MB
ubuntu latest 74435f89ab78 2 months ago 73.9MB
busybox 1.31.1-glibc 7a2331af2292 2 months ago 5.2MB
goproxy/goproxy latest e5878c746779 3 months ago 532MB
hello-world latest bf756fb1ae65 7 months ago 13.3kB

**Comment by nonsense** [comment]
@Cortze could you also report on why Grafana fails to start? It seems like the image is there, so checking the logs of the container would be helpful to determine what is wrong.

Maybe try:
```
docker ps -a | grep grafana
```

And also `docker ps`

**Comment by Cortze** [comment]
@nonsense here are the results for `docker ps -a | grep grafana` and `docker ps`
```~$ docker ps -a | grep grafana
beb11c619c21        bitnami/grafana             "/run.sh"                 24 seconds ago       Created                                                   testground-grafana
~$ docker ps 
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                     NAMES
50fc957bd56f        iptestground/sidecar:edge   "testground sidecar …"   2 weeks ago         Up 2 hours          0.0.0.0:32768->6060/tcp   testground-sidecar
7e1b748c827e        influxdb:1.8                "/entrypoint.sh infl…"   2 weeks ago         Up 52 seconds       0.0.0.0:8086->8086/tcp    testground-influxdb
fbfdb5d09062        redis                       "docker-entrypoint.s…"   2 weeks ago         Up 2 hours          0.0.0.0:6379->6379/tcp    testground-redis
3b217f126bf9        goproxy/goproxy             "/goproxy"               2 weeks ago         Up About a minute   8081/tcp                  testground-goproxy```

This is what the `testground daemon` reports:
```Sep  7 08:51:38.599911	INFO	build completed	{"req_id": "32bb813a", "default_tag": "8496fca4aba5:latest", "took": "36s"}
Sep  7 08:51:38.635188	INFO	got docker image id	{"req_id": "32bb813a", "image_id": "4d4e5a43b743"}
Sep  7 08:51:38.700061	INFO	tagging image	{"req_id": "32bb813a", "image_id": "4d4e5a43b743", "tag": "tg-plan-pubsub:4d4e5a43b743"}
Sep  7 08:51:38.704095	INFO	build succeeded	{"req_id": "32bb813a", "plan": "pubsub", "groups": ["publishers", "attackers", "lurkers"], "builder": "docker:go", "artifact": "4d4e5a43b743"}
Sep  7 08:51:38.704638	INFO	request handled	{"req_id": "32bb813a", "command": "build"}
Sep  7 08:51:38.706294	INFO	handle request	{"req_id": "90a07426", "command": "run"}
Sep  7 08:51:38.706534	INFO	performing healthcheck on runner	{"req_id": "90a07426"}
Sep  7 08:51:38.707992	INFO	container not found; creating	{"req_id": "90a07426", "container_name": "testground-grafana"}
latest: Pulling from bitnami/grafana
522a7372a4ae: Already exists
0bf5b121358b: Pulling fs layer
c22b7287675c: Pulling fs layer
523db28eadb6: Pulling fs layer
c9d2acbfe376: Pulling fs layer
e73926526163: Pulling fs layer
f59010ef8c5f: Pulling fs layer
82b68426a29f: Pulling fs layer
5af7e387f1b1: Pulling fs layer
c9d0fe58f02b: Pulling fs layer
c9d2acbfe376: Waiting
e73926526163: Waiting
f59010ef8c5f: Waiting
82b68426a29f: Waiting
5af7e387f1b1: Waiting
c9d0fe58f02b: Waiting
Sep  7 08:52:01.786996	INFO	created container	{"req_id": "90a07426", "container_name": "testground-grafana", "id": "beb11c619c219db39118737954ebfe1c6992143620bc547b9982841333f81742"}
Sep  7 08:52:01.787175	INFO	starting container	{"req_id": "90a07426", "container_name": "testground-grafana", "id": "beb11c619c219db39118737954ebfe1c6992143620bc547b9982841333f81742"}
Sep  7 08:52:02.005303	INFO	container isn't running; starting	{"req_id": "90a07426", "container_name": "testground-influxdb"}
Sep  7 08:52:02.591445	WARN	engine run error: healthcheck fixes failed; aborting:
Checks:
- local-outputs-dir: ok; directory exists.
- control-network: ok; network exists.
- local-grafana: failed; container not found.
- local-redis: ok; container state: running
- local-influxdb: failed; container state: exited
- sidecar-container: ok; container state: running
Fixes:
- local-outputs-dir: unnecessary; 
- control-network: unnecessary; 
- local-grafana: failed; failed to start container.
- local-redis: unnecessary; 
- local-influxdb: ok; container created.
- sidecar-container: unnecessary; 
	{"req_id": "90a07426"}
Sep  7 08:52:02.591527	INFO	request handled	{"req_id": "90a07426", "command": "run"}
```

**Comment by nonsense** [comment]
@Cortze could you check the logs for the Grafana container: `beb11c619c21` ?

The command is `docker logs beb11c619c21`

If the container is in `Created` state, it might be failing to start due to port collision on port 3000.

**Comment by Cortze** [comment]
@nonsense `docker logs beb11c619c21` doesn't report anything
But the port collision might be the problem, `sudo lsof -i -P -n | grep 3000` :
```
nghttpx     979            root    5u  IPv4  31551      0t0  TCP 127.0.0.1:3000 (LISTEN)
nghttpx    1025            root    5u  IPv4  31551      0t0  TCP 127.0.0.1:3000 (LISTEN)
```

**Comment by nonsense** [comment]
Right - I am not sure why we are swallowing this error, will follow up to fix!

It does looks like the port collision is the problem - the Grafana container is failing to start due to that.

**Comment by Cortze** [comment]
I've been able to free the port 3000 by uninstalling the nghttpx program and the problem while launching the grafana docker image gets solved.
